validation: sovereign
version: 1
build:
    proto:
        path: proto
accounts:
    - name: foundation
      coins:
        - 60000000000000000000000000unimo
    - name: alice
      coins:
        - 20000000000000000000000000unimo
    - name: bob
      coins:
        - 20000000000000000000000000unimo
faucet:
    name: bob
    coins:
        - 10000000000000000000unimo  # 10 nimo
    host: 0.0.0.0:4500
client:
    openapi:
        path: docs/static/openapi.json
default_denom: unimo
validators:
    - name: alice
      bonded: 10000000000000000000000unimo  # 10,000 nimo
    - name: validator1
      bonded: 10000000000000000000000unimo  # 10,000 nimo
      app:
        api:
            address: 0.0.0.0:1327
        grpc:
            address: 0.0.0.0:9100
        grpc-web:
            address: 0.0.0.0:9101
      config:
        p2p:
            laddr: 0.0.0.0:26666
        rpc:
            laddr: 0.0.0.0:26667
            pprof_laddr: 0.0.0.0:6070
    - name: validator2
      bonded: 10000000000000000000000unimo  # 10,000 nimo
      app:
        api:
            address: 0.0.0.0:1337
        grpc:
            address: 0.0.0.0:9110
        grpc-web:
            address: 0.0.0.0:9111
      config:
        p2p:
            laddr: 0.0.0.0:26676
        rpc:
            laddr: 0.0.0.0:26677
            pprof_laddr: 0.0.0.0:6080
